"""add health_records, medications, medication_administrations

Revision ID: 09f4a06bf040
Revises: 3912fe0a239e
Create Date: 2026-08-24 13:33:36.610232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f4a06bf040'
down_revision = '3912fe0a239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('pulse_bpm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wellbeing', sa.String(length=10), nullable=True),
    sa.Column('mood', sa.String(length=60), nullable=True),
    sa.Column('physical_activity', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_elderly_member_id'), ['elderly_member_id'], unique=False)

    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('administered_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_medication_id'), ['medication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_medication_id'))

    op.drop_table('medication_administrations')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_elderly_member_id'))

    op.drop_table('medications')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_records_elderly_member_id'))

    op.drop_table('health_records')
    # ### end Alembic commands ###
