"""add inbox messages

Revision ID: 0de524bd175b
Revises: e1229c95aca8
Create Date: 2026-08-24 16:10:54.321786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de524bd175b'
down_revision = 'e1229c95aca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_messages_created_at'))

    op.drop_table('inbox_messages')
    # ### end Alembic commands ###
