"""index donations and stock_movements created_at for reports

Revision ID: 186b45421053
Revises: a00119f7aac7
Create Date: 2026-08-24 15:13:20.632348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186b45421053'
down_revision = 'a00119f7aac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))

    # ### end Alembic commands ###
