"""add home_visits

Revision ID: 28ed9d8c5a00
Revises: 71c6cb8163c2
Create Date: 2026-08-24 13:52:05.131192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ed9d8c5a00'
down_revision = '71c6cb8163c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('support_provided', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_visits_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_visits_elderly_member_id'), ['elderly_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_visits_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_home_visits_assigned_to_id'))

    op.drop_table('home_visits')
    # ### end Alembic commands ###
