"""add activities, activity_participants

Revision ID: 51334549bb51
Revises: 994bb3668888
Create Date: 2026-08-24 14:36:32.987694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51334549bb51'
down_revision = '994bb3668888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('facilitator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('activity_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'elderly_member_id', name='uq_activity_participant_activity_member')
    )
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_participants_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_participants_elderly_member_id'), ['elderly_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_participants_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_activity_participants_activity_id'))

    op.drop_table('activity_participants')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_scheduled_at'))

    op.drop_table('activities')
    # ### end Alembic commands ###
