"""add meals, meal_attendance

Revision ID: 66fee7ca6af2
Revises: cd2b0420e5e6
Create Date: 2026-08-24 14:16:47.539397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fee7ca6af2'
down_revision = 'cd2b0420e5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planned_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_meal_date'), ['meal_date'], unique=False)

    op.create_table('meal_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id', 'elderly_member_id', name='uq_meal_attendance_meal_member')
    )
    with op.batch_alter_table('meal_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_attendance_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_attendance_meal_id'), ['meal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_attendance_meal_id'))
        batch_op.drop_index(batch_op.f('ix_meal_attendance_elderly_member_id'))

    op.drop_table('meal_attendance')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_meal_date'))

    op.drop_table('meals')
    # ### end Alembic commands ###
