"""extend donations for food/equipment types

Revision ID: cd2b0420e5e6
Revises: 28ed9d8c5a00
Create Date: 2026-08-24 14:08:46.646219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2b0420e5e6'
down_revision = '28ed9d8c5a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_type', sa.String(length=20), server_default='Cash', nullable=False))
        batch_op.add_column(sa.Column('item_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=True))
        batch_op.alter_column('donor_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('donor_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('item_description')
        batch_op.drop_column('donation_type')

    # ### end Alembic commands ###
