"""extend volunteer profile with application fields

Revision ID: d0e26ba03790
Revises: 4e6e039f08c4
Create Date: 2026-08-24 17:19:20.313434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e26ba03790'
down_revision = '4e6e039f08c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas_of_interest', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('motivation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_profiles', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('motivation')
        batch_op.drop_column('experience')
        batch_op.drop_column('areas_of_interest')

    # ### end Alembic commands ###
