"""add assignment attachments and messages

Revision ID: f40cbcf08509
Revises: d0e26ba03790
Create Date: 2026-08-24 18:46:01.737670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40cbcf08509'
down_revision = 'd0e26ba03790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_type', 'assignment_id', name='uq_assignment_attachment'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('assignment_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_messages', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_messages_assignment', ['assignment_type', 'assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_messages_created_at'))
        batch_op.drop_index('ix_assignment_messages_assignment')

    op.drop_table('assignment_messages')
    op.drop_table('assignment_attachments')
    # ### end Alembic commands ###
