"""add assignment started_at, volunteer concern reports, assignment checklist

Revision ID: f5d575e0403f
Revises: 75169e53eb90
Create Date: 2026-08-24 23:37:54.275332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d575e0403f'
down_revision = '75169e53eb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=40), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_type', 'assignment_id', 'item_key', name='uq_assignment_checklist_item')
    )
    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('elderly_member_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('elderly_member_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    op.drop_table('assignment_checklist_items')
    # ### end Alembic commands ###
