"""add follow-ups, incident severity, assistance follow-up fields

Revision ID: f79f61809d9c
Revises: f40cbcf08509
Create Date: 2026-08-24 19:33:27.709927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79f61809d9c'
down_revision = 'f40cbcf08509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index('ix_follow_ups_elderly_status', ['elderly_member_id', 'status'], unique=False)
        batch_op.create_index('ix_follow_ups_source', ['source_type', 'source_id'], unique=False)

    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_up_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('follow_up_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('severity')

    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.drop_column('follow_up_notes')
        batch_op.drop_column('follow_up_required')

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index('ix_follow_ups_source')
        batch_op.drop_index('ix_follow_ups_elderly_status')
        batch_op.drop_index(batch_op.f('ix_follow_ups_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_created_at'))

    op.drop_table('follow_ups')
    # ### end Alembic commands ###
