"""add home visit review workflow

Revision ID: ff31649c7157
Revises: b3e7a1c9f402
Create Date: 2026-09-10 23:31:52.029082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff31649c7157'
down_revision = 'b3e7a1c9f402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_visit_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_visit_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('return_sections', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['home_visit_id'], ['home_visits.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_visit_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_visit_submissions_home_visit_id'), ['home_visit_id'], unique=False)

    # NOTE: autogenerate also detected unrelated pre-existing drift on
    # follow_ups' indexes and volunteer_invitations' token uniqueness —
    # left untouched here on purpose, out of scope for this migration.

    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wellbeing', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pulse_bpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temperature_celsius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('physical_activity', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('basic_needs_confirmed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('concerns_discussed', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('return_sections', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_home_visits_reviewed_by_id_users', 'users', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_home_visits_reviewed_by_id_users', type_='foreignkey')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('return_sections')
        batch_op.drop_column('return_reason')
        batch_op.drop_column('returned_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('concerns_discussed')
        batch_op.drop_column('basic_needs_confirmed')
        batch_op.drop_column('physical_activity')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('temperature_celsius')
        batch_op.drop_column('pulse_bpm')
        batch_op.drop_column('blood_pressure_diastolic')
        batch_op.drop_column('blood_pressure_systolic')
        batch_op.drop_column('mood')
        batch_op.drop_column('wellbeing')

    with op.batch_alter_table('home_visit_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_visit_submissions_home_visit_id'))

    op.drop_table('home_visit_submissions')
    # ### end Alembic commands ###
